import { describe, it, expect } from 'vitest'
import { readFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { unzipSync, strFromU8 } from 'fflate'
import { scanMedia, hideSlides, setShowFalse, classifyUrl, mediaFilenames, mediaBytes } from '../src/core/media'
import { readZipDirectory, storedZip, crc32 } from '../src/core/zipdir'

/**
 * test/fixtures/media.pptx is generated by scripts/make-media-deck.mjs and
 * committed. Its slide XML copies what PowerPoint writes in real decks.
 */
const fixture = (name: string) => fileURLToPath(new URL(`./fixtures/${name}`, import.meta.url))
const deck = () => new Uint8Array(readFileSync(fixture('media.pptx')))
const concat = (parts: Uint8Array[]) => {
  const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0))
  let o = 0
  for (const p of parts) out.set(p, o), (o += p.length)
  return out
}

describe('media scan', () => {
  it('numbers slides in show order, not by file name', () => {
    const r = scanMedia(deck())
    expect(r.slides.map((s) => s.part.replace('ppt/slides/', ''))).toEqual([
      'slide3.xml', 'slide1.xml', 'slide2.xml', 'slide4.xml',
      'slide5.xml', 'slide6.xml', 'slide7.xml', 'slide8.xml',
    ])
    expect(r.slides[0]!.title).toBe('Welcome & intro')
    expect(r.slides[3]!.hidden).toBe(true)
    expect(r.slides.filter((s) => s.hidden)).toHaveLength(1)
  })

  it('counts a video once, though PowerPoint links it twice', () => {
    const r = scanMedia(deck())
    const onFirst = r.placements.filter((p) => p.slide === 1)
    expect(onFirst).toHaveLength(1)
  })

  it('keeps one file used on several slides as one file', () => {
    const r = scanMedia(deck())
    const intro = r.files.find((f) => f.part === 'ppt/media/media1.mp4')!
    expect(intro.slides).toEqual([1, 2])
    expect(r.files).toHaveLength(7)
  })

  it('reads the playback settings off the timing tree', () => {
    const r = scanMedia(deck())
    const first = r.placements.find((p) => p.slide === 1)!
    expect(first.playback).toMatchObject({
      start: 'automatically',
      loop: true,
      fullScreen: true,
      volume: 50,
      hideWhenStopped: true,
      trimStartMs: 1500,
      trimEndMs: 250.5,
    })
    const second = r.placements.find((p) => p.slide === 2)!
    expect(second.playback.start).toBe('when-clicked-on')
  })

  it('probes codecs and gives a per-platform verdict', () => {
    const r = scanMedia(deck())
    const by = (part: string) => r.files.find((f) => f.part === `ppt/media/${part}`)!
    expect(by('media1.mp4').probe.video).toMatchObject({ codec: 'H.264', profile: 'High', bitDepth: 8, width: 64, height: 36, fps: 25 })
    expect(by('media1.mp4').probe.audio?.codec).toBe('AAC')
    expect(by('media1.mp4').compat).toMatchObject({ windows: 'yes', mac: 'yes', verdict: 'good' })

    expect(by('media2.mp4').probe.video).toMatchObject({ profile: 'High 10', bitDepth: 10 })
    expect(by('media2.mp4').compat).toMatchObject({ windows: 'no', mac: 'no', verdict: 'bad' })

    expect(by('media3.mp4').compat).toMatchObject({ windows: 'extension', mac: 'no' })
    expect(by('media4.mov').compat).toMatchObject({ windows: 'no', mac: 'yes' })
    expect(by('media4.mov').probe.container).toBe('mov')
    expect(by('media5.wmv').compat).toMatchObject({ windows: 'yes', mac: 'no' })
    expect(by('media6.mp3')).toMatchObject({ kind: 'audio', compat: { verdict: 'good' } })
  })

  it('finds every way a slide reaches for the internet', () => {
    const r = scanMedia(deck())
    const online = r.placements.filter((p) => p.source === 'online')
    const summary = online.map((p) => p.source === 'online' && `${p.slide} ${p.via} ${p.online.service}`)
    expect(summary).toEqual([
      '3 online-video youtube',
      '3 hyperlink vimeo',
      '5 online-video stream',
      '5 flash youtube',
      '5 add-in vimeo',
    ])
    // An ordinary web link is not media.
    expect(online.some((p) => p.source === 'online' && p.url.includes('example.com'))).toBe(false)
  })

  it('reports a video linked from disk as linked, not embedded', () => {
    const r = scanMedia(deck())
    const linked = r.placements.filter((p) => p.source === 'linked')
    expect(linked).toHaveLength(1)
    expect(linked[0]).toMatchObject({ slide: 4, shape: 'Linked clip' })
  })

  it('puts a layout video on every slide built from the layout', () => {
    const r = scanMedia(deck())
    const loop = r.placements.filter((p) => p.source === 'embedded' && p.part.endsWith('media7.mp4'))
    expect(loop.map((p) => [p.slide, p.inheritedFrom])).toEqual([[7, 'layout'], [8, 'layout']])
  })

  it('names extracted files after slide and shape', () => {
    const names = mediaFilenames(scanMedia(deck()))
    expect(names.get('ppt/media/media1.mp4')).toBe('Slide 1 - Intro film.mp4')
    expect(names.get('ppt/media/media4.mov')).toBe('Slide 6 - ProRes master.mov')
    expect(new Set(names.values()).size).toBe(names.size)
  })
})

describe('classifyUrl', () => {
  it.each([
    ['https://youtu.be/abc', 'youtube', false],
    ['https://www.youtube-nocookie.com/embed/abc', 'youtube', false],
    ['https://contoso-my.sharepoint.com/personal/x/Documents/a.mp4', 'onedrive-business', true],
    ['https://contoso.sharepoint.com/sites/x/Shared%20Documents/a.mp4', 'sharepoint', true],
    ['https://onedrive.live.com/embed?cid=1', 'onedrive', false],
    ['https://web.microsoftstream.com/video/1', 'stream-classic', true],
  ])('%s -> %s', (url, service, signIn) => {
    expect(classifyUrl(url)).toMatchObject({ service, signIn })
  })

  it('knows Stream (Classic) is gone', () => {
    expect(classifyUrl('https://web.microsoftstream.com/video/1').retired).toBe(true)
  })
})

describe('hiding slides', () => {
  it('sets show="0" and keeps the rest of the root element', () => {
    expect(setShowFalse('<?xml version="1.0"?><p:sld xmlns:p="x">')).toBe('<?xml version="1.0"?><p:sld xmlns:p="x" show="0">')
    expect(setShowFalse('<p:sld show="1" xmlns:p="x"><p:sldLayout/>')).toBe('<p:sld show="0" xmlns:p="x"><p:sldLayout/>')
  })

  it('rewrites the deck with only those slides changed, media byte for byte', () => {
    const src = deck()
    const out = concat(hideSlides(src, ['ppt/slides/slide3.xml', 'ppt/slides/slide6.xml']))

    // Reads back with an independent zip reader, CRCs checked.
    const files = unzipSync(out)
    const orig = unzipSync(src)
    expect(Object.keys(files).sort()).toEqual(Object.keys(orig).sort())
    for (const name of Object.keys(orig)) {
      if (name === 'ppt/slides/slide3.xml' || name === 'ppt/slides/slide6.xml') continue
      expect(files[name], name).toEqual(orig[name])
    }
    expect(strFromU8(files['ppt/slides/slide3.xml']!)).toMatch(/<p:sld [^>]*show="0"/)

    const again = scanMedia(out)
    expect(again.slides.filter((s) => s.hidden).map((s) => s.number)).toEqual([1, 4, 6])

    // Unchanged entries keep their stored method: media stays uncompressed.
    const dir = readZipDirectory(out)
    expect(dir.byName.get('ppt/media/media1.mp4')!.method).toBe(0)
    expect(dir.byName.get('ppt/slides/slide3.xml')!.method).toBe(8)
  })
})

describe('saving media', () => {
  it('returns the stored bytes as a view, and zips them intact', () => {
    const src = deck()
    const bytes = mediaBytes(src, 'ppt/media/media1.mp4')
    expect(bytes.buffer).toBe(src.buffer) // a view, not a copy
    expect(String.fromCharCode(...bytes.subarray(4, 8))).toBe('ftyp')

    const zip = concat(storedZip([{ name: 'Slide 1 - Intro film.mp4', data: bytes }, { name: 'MANIFEST.txt', data: new TextEncoder().encode('hi') }]))
    const back = unzipSync(zip)
    expect(back['Slide 1 - Intro film.mp4']).toEqual(bytes)
    expect(strFromU8(back['MANIFEST.txt']!)).toBe('hi')
  })

  it('agrees with the deck on CRC-32', () => {
    const src = deck()
    const e = readZipDirectory(src).byName.get('ppt/media/media6.mp3')!
    expect(crc32(mediaBytes(src, e.name))).toBe(e.crc)
  })
})

// The real decks are private; see AGENTS.md §7.
const has = (n: string) => existsSync(fixture(n))
describe('real decks', () => {
  it.runIf(has('themeref-heavy.pptx'))('finds nothing in a deck whose one video sits on an unused layout', () => {
    const r = scanMedia(new Uint8Array(readFileSync(fixture('themeref-heavy.pptx'))))
    expect(r.placements).toHaveLength(0)
    expect(r.slides).toHaveLength(33)
  })
})
